extends: ".eslintrc.yml"
rules:
  "@typescript-eslint/space-before-function-paren": warn
  "@typescript-eslint/no-extra-semi": warn
  "@typescript-eslint/no-extra-parens": warn
  "@typescript-eslint/brace-style":
    - warn
    - stroustrup
  "@typescript-eslint/func-call-spacing": warn
  "@typescript-eslint/member-delimiter-style":
    - warn
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  padded-blocks: warn
  no-trailing-spaces:
    - warn
    - skipBlankLines: true
  no-multiple-empty-lines: warn
  multiline-comment-style: warn
  capitalized-comments: warn
  quote-props:
    - warn
    - as-needed
  function-paren-newline:
    - warn
    - consistent
  space-before-function-paren: warn
  object-property-newline:
    - warn
    - allowAllPropertiesOnSameLine: true
  lines-around-comment: warn
  comma-dangle:
    - warn
    - arrays: always-multiline
      objects: always-multiline
      imports: never
      exports: never
      functions: never
  eol-last: warn
  newline-per-chained-call: warn
  array-element-newline:
    - warn
    - minItems: 3
  arrow-parens:
    - warn
    - as-needed
  "@typescript-eslint/quotes":
    - error
    - single
  dot-location:
    - warn
    - property
  object-curly-spacing: warn
  spaced-comment: warn
  object-shorthand: warn
  template-curly-spacing: warn
  lines-between-class-members: warn
  space-in-parens: warn
  "@typescript-eslint/indent":
    - warn
    - tab
  key-spacing: warn
  new-parens: warn
  space-infix-ops: warn
  space-before-blocks: warn
  no-useless-rename: warn
  "@typescript-eslint/semi":
    - warn
    - never
  no-multi-spaces: warn
  curly:
    - warn
    - multi
