version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: weekly
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          update_type: all
          dependency_type: all
