name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - depfu
  pull_request:
    branches:
      - '*'

jobs:
  build:
    timeout-minutes: 5

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      postgres:
        image: postgres:12.1
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: secrets usage example
        run: echo ${{secrets.MY_SECRET}}
      - name: install
        run: yarn install
      - name: start-test (for schema generation)
        run: yarn start-test
        timeout-minutes: 2
      - name: generate types
        run: yarn codegen
      - name: typecheck
        run: yarn typecheck
      - name: test
        run: yarn jest

        env:
          CI: true
